version: "3.7"
services:
  db:
    image: postgres:13.3
    container_name: db_app
    command: -p 2211
    expose:
      - 2211
    env_file:
      - .env-non-dev
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app
    command: ["redis-server", "--port", "3344"]
    expose:
      - 3344
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 80:8000
    depends_on:
      - db
      - redis
    volumes:
      - .:/fastapi_app
      - static_volume:/fastapi_app/src/static

  celery:
    build:
      context: .
    container_name: celery_app
    env_file:
      - .env-non-dev
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis
    volumes:
      - .:/fastapi_app

  flower:
    build:
      context: .
    container_name: flower_app
    env_file:
      - .env-non-dev
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
    volumes:
      - .:/fastapi_app
      
volumes:
  db_data:
  redis_data:
  static_volume:


